from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "data" / "reports"
DOCS_DIR = ROOT / "docs"
OUTPUT_FILE = DOCS_DIR / "sample_report_preview.md"


def markdown_table(df: pd.DataFrame, max_rows: int = 10) -> str:
    preview = df.head(max_rows).copy()

    def clean(value):
        return str(value).replace("|", "\\|").replace("\n", " ")

    headers = [clean(col) for col in preview.columns]
    rows = [[clean(value) for value in row] for row in preview.values]

    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for row in rows:
        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines)


def section_for_report(filename: str, title: str, description: str) -> str:
    path = REPORTS_DIR / filename

    if not path.exists():
        return "\n".join([
            f"## {title}",
            "",
            f"Report file not found: `{filename}`",
            "",
        ])

    df = pd.read_csv(path)

    return "\n".join([
        f"## {title}",
        "",
        f"**File:** `data/reports/{filename}`",
        "",
        description,
        "",
        f"**Rows:** {len(df)}",
        "",
        markdown_table(df),
        "",
        "",
    ])


def main() -> None:
    DOCS_DIR.mkdir(exist_ok=True)

    sections = [
        "# Sample Report Preview",
        "",
        "This document previews the CSV exception reports generated by the Trade Reconciliation SQL Project.",
        "",
        "The reports are created from simulated data and show how a trading operations analyst might review daily reconciliation breaks.",
        "",
        "---",
        "",
        section_for_report(
            "reconciliation_summary.csv",
            "Reconciliation Summary",
            "Summarizes exception counts by break type.",
        ),
        section_for_report(
            "trade_exceptions.csv",
            "Trade Exceptions",
            "Shows trade-level breaks between internal bookings and broker-reported trades.",
        ),
        section_for_report(
            "duplicate_trade_exceptions.csv",
            "Duplicate Trade Exceptions",
            "Identifies duplicate execution IDs in internal or broker trade records.",
        ),
        section_for_report(
            "allocation_exceptions.csv",
            "Allocation Exceptions",
            "Shows account-level allocation breaks between internal and broker allocation records.",
        ),
        "---",
        "",
        "## How to Regenerate These Reports",
        "",
        "```bash",
        "make run",
        "python src/export_report_preview.py",
        "```",
        "",
    ]

    OUTPUT_FILE.write_text("\n".join(sections))
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
